'use client';
import {banks,display,rankedExposure,type Snapshot,type WorldData,type Mode,type Exposure} from '@/lib/world/model';
export function ExposurePanel({bank,onExposure,data}:{bank:Snapshot|undefined;onExposure:(e:Exposure)=>void;data:WorldData|null}){
 const rows=rankedExposure(bank?.exposures??[]);const amount=rows.length>0&&rows.every(e=>e.amount!==null);
 return <div className="exposure-panel"><div className="eyebrow">WHERE THE MONEY GOES</div><h3>{bank?.ticker??'เลือกธนาคาร'} · ปลายทางสินเชื่อ</h3><p className="data-warning">ข้อมูลจากชุด RAG ที่นำเข้า · ยังไม่ได้ตรวจต้นฉบับซ้ำ</p>
 {!rows.length?<p>DATA NOT AVAILABLE<br/><small>ไม่มี Loan mix สำหรับธนาคารนี้ในชุดข้อมูล จึงไม่สร้างสัดส่วนหรือเส้นความกระจุกตัวขึ้นเอง</small></p>:<><p className="muted">{rows[0].taxonomy}<br/>Loan mix: {rows[0].period}<br/>งบหลัก: {bank?.period}</p>{rows[0].company&&<p className="data-warning">เป็นสัดส่วนตามบริษัทในกลุ่ม ไม่ใช่การแบ่งภาคเศรษฐกิจ</p>}
 <div className="ranked-exposures">{rows.map((e,i)=><button key={e.category} onClick={()=>onExposure(e)}><span>{String(i+1).padStart(2,'0')}</span><div><b>{e.category}</b><small>{amount?display(e.amount,' ล้านบาท'):display(e.share,'%')}</small></div><em>↗</em></button>)}</div>
 <details><summary>วิธีอ่านความหนาของเส้น</summary><p>ความหนาแปรตามรากที่สองของขนาดเทียบรายการสูงสุดภายในธนาคารเดียวกัน ใช้จำนวนเงินเมื่อมีครบทุกหมวด มิฉะนั้นใช้สัดส่วนที่รายงาน ไม่ได้แสดงสัดส่วนต่อสินทรัพย์ทั้งหมด และไม่ใช้ความหนาข้ามธนาคารเพื่อเปรียบเทียบขนาด</p><p>ตัดรายการรวมที่ซ้อนกับรายการย่อยออก ไม่มีการรวม Retail กับสินเชื่อย่อยซ้ำ หมวดสินเชื่ออาจไม่เท่ากับภาคอุตสาหกรรม</p><p>{rows[0].note}</p></details>
 {data?.sources.filter(s=>rows.some(e=>e.source===s.id)).map(s=><a className="source-link" key={String(s.id)} href={String(s.url)} target="_blank" rel="noreferrer">{String(s.title)} ↗<small>{String(s.period)} · {String(s.published??'ไม่ระบุวันเผยแพร่')}</small></a>)}
 </>}
 </div>
}
export function MarketPanel({bank,data}:{bank:Snapshot|undefined;data:WorldData|null}){return <div className="market-panel"><div className="eyebrow">VALUATION GALAXY</div><h3>{bank?.ticker??'ROE × P/BV'}</h3><p>ตำแหน่ง X คือ P/BV · Y คือ ROE · ขนาดทรงกลมคือ Market cap</p><p className="data-warning">ไม่มี Earnings growth ในชุดนี้ จึงยังไม่เข้ารหัสแกน Z ตำแหน่งบนระนาบไม่ใช่ growth = 0</p>{bank&&<><dl>{[['P/BV',display(bank.pbv,'×')],['ROE',display(bank.roe,'%')],['P/E',display(bank.pe,'×')],['Market cap',display(bank.marketCap,' ล้านบาท')],['Earnings growth',display(bank.growth,'%')],['งบการเงิน',bank.period],['Market snapshot',bank.marketDate]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><p className="muted">{bank.scope}</p><p>{bank.marketNote}</p></>}
 <p className="muted">ข้อมูลนำเข้า ยังไม่ได้ตรวจต้นฉบับซ้ำ ราคาตลาดและงบการเงินอาจคนละงวด ไม่ได้ปรับให้เป็นวันเดียวกัน</p><p>P/BV ต่ำไม่ได้แปลว่าราคาถูกเสมอ ต้องพิจารณาความยั่งยืนของ ROE การเติบโต ความเสี่ยง และเงินกองทุนร่วมกัน</p>{data?.sources.filter(s=>bank&&s.entity===bank.ticker&&String(s.id).includes('SET')).map(s=><a className="source-link" href={String(s.url)} key={String(s.id)} target="_blank" rel="noreferrer">{String(s.title)} ↗</a>)}</div>}
export function ComparePanel({selected,data,onToggle}:{selected:string[];data:WorldData|null;onToggle:(s:string)=>void}){return <div><div className="eyebrow">SIDE BY SIDE</div><h3>เลือกสูงสุด 3 ธนาคาร</h3><div className="comparison-picker">{banks.map(b=><button key={b.ticker} disabled={!selected.includes(b.ticker)&&selected.length===3} aria-pressed={selected.includes(b.ticker)} onClick={()=>onToggle(b.ticker)}>{b.ticker}</button>)}</div><p className="muted">Imported data · อ่านงวดและขอบเขตแต่ละแห่งก่อนเปรียบเทียบ</p>{selected.map(t=>{const b=data?.banks.find(x=>x.ticker===t);return b?<details key={t} open><summary>{t} · {b.period}</summary><p className="muted">{b.scope}</p><dl>{[['ROE',display(b.roe,'%')],['NIM',display(b.nim,'%')],['NPL',display(b.npl,'%')],['Credit cost',display(b.creditCost,' bps')],['CAR',display(b.car,'%')],['สินทรัพย์',display(b.assets,' ล้านบาท')],['สินเชื่อ',display(b.loans,' ล้านบาท')],['เงินฝาก',display(b.deposits,' ล้านบาท')],['กำไรไตรมาส',display(b.profit,' ล้านบาท')]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><small>{b.sources}</small></details>:null})}</div>}
