'use client';
import dynamic from 'next/dynamic';
import Image from 'next/image';
import {useCallback,useEffect,useState} from 'react';
import WorldBoundary from '@/components/WorldBoundary';
import ResearchPanel from '@/components/ResearchPanel';
import {ExposurePanel,MarketPanel,ComparePanel} from '@/components/world/WorldPanel';
import type {Stream} from '@/components/world/MoneyNetwork';
import {banks,modes,origins,sectors,engines,tour,type Bank,type Mode,type WorldData,type V3,type Place,type Exposure,display} from '@/lib/world/model';
import {sections,connections,type SectionId} from '@/lib/bank-sections';
const BankWorld=dynamic(()=>import('@/components/BankWorld'),{ssr:false});
export default function Home(){
 const [worldReady,setWorldReady]=useState(false);const markReady=useCallback(()=>setWorldReady(true),[]);
 const [selected,setSelected]=useState<Bank|null>(null),[interior,setInterior]=useState(false),[section,setSection]=useState<SectionId|null>(null),[metric,setMetric]=useState<string|null>(null),[expanded,setExpanded]=useState(true);
 const [mode,setMode]=useState<Mode>('overview'),[data,setData]=useState<WorldData|null>(null),[dataError,setDataError]=useState(false),[reload,setReload]=useState(0),[beginner,setBeginner]=useState(true),[low,setLow]=useState(false);
 const [focus,setFocus]=useState<V3|null>(null),[place,setPlace]=useState<Place|null>(null),[sector,setSector]=useState<string|null>(null),[stream,setStream]=useState<Stream|null>(null),[exposure,setExposure]=useState<Exposure|null>(null),[nonce,setNonce]=useState(0);
 const [journey,setJourney]=useState(0),[step,setStep]=useState(0),[finished,setFinished]=useState(false),[paused,setPaused]=useState(false),[stress,setStress]=useState(.25),[comparison,setComparison]=useState<string[]>([banks[0].ticker,banks[1].ticker]);
 const [researchView,setResearchView]=useState<'overview'|'evidence'|'sources'>('overview');
 const snapshot=data?.banks.find(b=>b.ticker===selected?.ticker);
 useEffect(()=>{const abort=new AbortController();setDataError(false);fetch('/api/bank-world',{signal:abort.signal}).then(r=>{if(!r.ok)throw Error();return r.json()}).then(setData).catch(e=>{if(e.name!=='AbortError')setDataError(true)});return()=>abort.abort()},[reload]);
 const clear=()=>{setJourney(0);setFinished(false);setPaused(false);setStream(null);setExposure(null);setPlace(null);setFocus(null);setSector(null);setMetric(null)};
 const changeMode=(next:Mode)=>{clear();setMode(next);setInterior(false);setSection(null);setNonce(n=>n+1);if(['concentration','sectors'].includes(next)&&!selected)setSelected(banks[0])};
 const choose=(b:Bank)=>{clear();setSelected(b);setInterior(false);setSection(null);setResearchView('overview');if(!['concentration','sectors','compare','valuation'].includes(mode))setMode('district');setNonce(n=>n+1)};
 const enter=(b:Bank)=>{clear();setSelected(b);setMode('district');setInterior(true);setSection('funding');setResearchView('overview')};
 const openSection=(s:SectionId)=>{setJourney(0);setFinished(false);setFocus(null);setPlace(null);setStream(null);setMode('district');setSelected(selected??banks[0]);setInterior(true);setSection(s);setMetric(null);setResearchView('overview')};
 const overview=()=>{clear();setSelected(null);setInterior(false);setSection(null);setMode('overview');setNonce(n=>n+1)};
 const startJourney=()=>{clear();setSelected(selected??banks[0]);setInterior(false);setMode('flow');setStep(0);setJourney(n=>n+1)};
 const complete=useCallback(()=>{setJourney(0);setFinished(true);setMode('profit')},[]);
 const onPlace=(p:Place)=>{clear();setPlace(p);setFocus(p.position);setInterior(false);if(sectors.some(s=>s.id===p.id)){setMode('sectors');setSector(p.id)}else setMode(origins.some(o=>o.id===p.id)?'funding':p.id==='risk'||p.id==='provision'?'risk':'profit')};
 const onStream=(s:Stream)=>{setStream(s);setExposure(null);setJourney(0)};
 const selectExposure=(e:Exposure)=>{setExposure(e);setStream(null);if(e.destination){const target=sectors.find(s=>s.id===e.destination);if(target)setFocus(target.position)}};
 const onValuation=(ticker:string,p:V3)=>{clear();setSelected(banks.find(b=>b.ticker===ticker)??null);setFocus(p);setMode('valuation')};
 const toggleCompare=(s:string)=>setComparison(a=>a.includes(s)?a.filter(x=>x!==s):a.length<3?[...a,s]:a);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.target as HTMLElement)?.closest('input,select,textarea,button'))return;if(e.key==='Escape'){setJourney(0);setFinished(false)}if(e.code==='Space'&&journey){e.preventDefault();setPaused(p=>!p)}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[journey]);
 const rightOpen=!!selected||mode==='compare'||mode==='valuation'||mode==='risk';
 return <main className={`bank-app v3 ${journey?'is-journey':''}`}>
 <WorldBoundary><BankWorld onReady={markReady} selected={selected} onSelect={choose} onEnter={enter} interior={interior} expanded={expanded} section={section} metric={metric} onSection={openSection} onMetric={setMetric} mode={mode} data={data} sector={sector} onPlace={onPlace} onStream={onStream} journey={journey} paused={paused} onStep={setStep} onComplete={complete} focus={focus} nonce={nonce} stress={stress} comparison={comparison} low={low} onValuation={onValuation}/></WorldBoundary>
 <header className="brand-header"><button className="brand-home" onClick={overview} aria-label="หนุ่มนักออม — กลับสู่ภาพรวม"><Image className="brand-logo" src="/brand/noom-nak-aom.png" alt="" width={48} height={48} sizes="(max-width: 650px) 38px, 48px" priority/><div className="brand-wordmark"><span>หนุ่มนักออม</span><strong>THAI BANK MONEY MAP</strong></div></button><div className="header-caption">เข้าใจหุ้นแบงก์ ผ่านเส้นทางของเงิน</div><div className="header-settings"><button onClick={()=>setBeginner(b=>!b)}>{beginner?'BEGINNER':'INVESTOR'}</button><button onClick={()=>setLow(v=>!v)} aria-pressed={low}>{low?'คุณภาพเบา':'คุณภาพสูง'}</button></div></header>
 <nav className="exploration-modes" aria-label="มุมมองการสำรวจ">{modes.map(m=><button key={m.id} onClick={()=>changeMode(m.id)} aria-pressed={mode===m.id}>{m.label}</button>)}</nav>
 <div className="world-navigation"><button onClick={overview}>THAI BANKING WORLD</button>{selected&&<><span>›</span><button onClick={()=>choose(selected)}>{selected.ticker}</button></>}{section&&<><span>›</span><span>{sections.find(s=>s.id===section)?.label}</span></>}</div>
 <aside className="stack-navigation"><small>{modes.find(m=>m.id===mode)?.en}</small><h1>{interior?selected?.ticker:'เงินฝาก\nไม่ได้หยุด\nอยู่ในบัญชี'}</h1><p>{interior?'สำรวจกลไกภายในธนาคาร':'ตามเงิน ตามความเสี่ยง ตามกำไร แล้วค่อยดูราคา'}</p><button className="hero-follow" disabled={!worldReady} title={worldReady?'เดินทางตามอนุภาคในโลก 3D':'รอฉาก 3D พร้อมใช้งาน'} onClick={startJourney}>▶ FOLLOW ฿100 <b>↗</b></button><div className="stack-title">{interior?'ภายในธนาคาร · 6 ชั้น':mode==='funding'?'ต้นทางเงินทุน':mode==='sectors'?'ปลายทางในเศรษฐกิจ':'เลือกธนาคาร · 7 แห่ง'}</div>
 {interior?sections.map((s,i)=><button key={s.id} className={section===s.id?'active':''} onClick={()=>openSection(s.id)}><span>{String(i+1).padStart(2,'0')}</span>{s.label}<b>›</b></button>):mode==='funding'||mode==='sectors'?(mode==='funding'?origins:sectors).map((p,i)=><button key={p.id} className={place?.id===p.id?'active':''} onClick={()=>onPlace(p)}><span>{String(i+1).padStart(2,'0')}</span>{p.label}<b>›</b></button>):banks.map((b,i)=><button key={b.ticker} className={selected?.ticker===b.ticker?'active':''} onClick={()=>choose(b)}><span>{String(i+1).padStart(2,'0')}</span>{b.ticker}<b>›</b></button>)}
 <p className="schematic-note">รูปทรงอาคารและย่านเป็นแบบจำลอง ไม่ใช่ขนาดสินทรัพย์หรือสำนักงานใหญ่จริง</p></aside>
 {rightOpen&&!journey&&<aside className="research-panel"><div className="panel-heading"><div><small>{interior?'INSIDE THE BANK':modes.find(m=>m.id===mode)?.en}</small><h2>{selected?.ticker??(mode==='compare'?'COMPARE':mode==='risk'?'CREDIT STRESS':'VALUATION')}</h2></div><button onClick={()=>{setSelected(null);setInterior(false);setSection(null);setMode('overview')}} aria-label="ปิดรายละเอียด">✕</button></div>
 {dataError&&<p role="alert">โหลดข้อมูลไม่สำเร็จ <button onClick={()=>setReload(n=>n+1)}>ลองอีกครั้ง</button></p>}
 {mode==='risk'&&<div className="risk-controller"><p>จำลองความเสี่ยงผ่านอนุภาคที่ช้าลง ค้างสะสม และกำไรที่เหลือลดลง</p><label htmlFor="credit-stress">ระดับความเครียดเชิงภาพ: {Math.round(stress*100)} / 100</label><input id="credit-stress" type="range" min="0" max="1" step=".05" value={stress} onChange={e=>setStress(Number(e.target.value))}/><p className="data-warning">ILLUSTRATIVE · ไม่ใช่อัตรา NPL หรือประมาณการของแบงก์ ไม่คำนวณกำไรจริงจาก slider นี้</p></div>}
 {mode==='compare'?<ComparePanel selected={comparison} data={data} onToggle={toggleCompare}/>:mode==='valuation'?<MarketPanel bank={snapshot} data={data}/>:mode==='concentration'||mode==='sectors'?<ExposurePanel bank={snapshot} data={data} onExposure={selectExposure}/>:selected&&<>
 {!interior?<button className="enter-bank" onClick={()=>enter(selected)}>เข้าไปในตึก →</button>:<><nav className="floor-tabs" aria-label="ชั้นธุรกิจ">{sections.map(s=><button key={s.id} className={section===s.id?'active':''} onClick={()=>openSection(s.id)}>{s.label}</button>)}</nav><button className="explode-button" onClick={()=>setExpanded(v=>!v)}>{expanded?'รวมชั้นตึก':'แยกชั้นตึกเพื่อสำรวจ'} ↗</button></>}
 {section&&beginner&&<div className="layer-context"><small>THE INVESTMENT CONNECTION</small><p>{connections[section].why}</p>{(['upstream','downstream'] as const).map(direction=><div key={direction}><span>{direction==='upstream'?'ต้นทาง':'ปลายทาง'}</span>{connections[section][direction].map(id=><button key={id} onClick={()=>openSection(id)}>{sections.find(s=>s.id===id)?.label} ↗</button>)}</div>)}</div>}
 <div className="research-switch"><button aria-pressed={researchView==='overview'} onClick={()=>setResearchView('overview')}>ข้อมูล</button><button aria-pressed={researchView==='evidence'} onClick={()=>setResearchView('evidence')}>หลักฐาน</button><button aria-pressed={researchView==='sources'} onClick={()=>setResearchView('sources')}>แหล่งอ้างอิง</button></div><ResearchPanel key={selected.ticker} ticker={selected.ticker} section={section??'funding'} metric={metric} onMetric={setMetric} view={researchView}/>
 </>}
 </aside>}
 {(place||stream||exposure)&&!journey&&<section className="flow-inspector"><button className="close-inspector" onClick={()=>{setPlace(null);setStream(null);setExposure(null)}} aria-label="ปิดคำอธิบายเส้นเงิน">×</button><small>{exposure||stream?.source?'IMPORTED EXPOSURE':'EDUCATIONAL RELATIONSHIP'}</small><h3>{exposure?.category??(stream?`${stream.from} → ${stream.to}`:place?.label)}</h3>{exposure||stream?.source?<><p>{display((exposure??stream?.source)?.amount,' ล้านบาท')} · สัดส่วน {display((exposure??stream?.source)?.share,'%')}</p><small>{(exposure??stream?.source)?.taxonomy} · {(exposure??stream?.source)?.period}<br/>{(exposure??stream?.source)?.source}</small><p>{(exposure??stream?.source)?.note}</p></>:<p>{mode==='sectors'?'ย่านนี้ใช้เล่าเศรษฐกิจ เส้น Exposure จะปรากฏเฉพาะหมวดสินเชื่อที่มีข้อมูลรองรับ ไม่ได้ถือว่าหมวดสินเชื่อธุรกิจทั้งหมดเป็นอุตสาหกรรมนี้':'เส้นทางและปริมาณอนุภาคเป็นภาพอธิบาย ไม่ใช่สัดส่วนเงินจริงหรือผลการดำเนินงานของบริษัท'}</p>}</section>}
 {(journey||finished)&&<section className="journey-caption-v3" aria-live="polite"><div><small>{finished?'JOURNEY COMPLETE':`${String(step+1).padStart(2,'0')} / 12 · ${tour[step][2]}`}</small><button onClick={()=>{setJourney(0);setFinished(false)}} aria-label="จบการเดินทาง">✕</button></div><h2>{finished?'ตามเงิน ตามความเสี่ยง แล้วค่อยดูราคา':tour[step][0]}</h2><p>{finished?'เงินฝากรองรับสินทรัพย์ กิจกรรมเศรษฐกิจสร้างรายได้ และกำไรอาจกลับไปยังผู้ถือหุ้น':tour[step][1]}</p><div className="story-progress">{tour.map((_,i)=><i key={i} className={i<=step?'passed':''}/>)}</div><small>EDUCATIONAL SIMPLIFIED MODEL · ไม่ใช่การติดตามเงินจริง</small>{journey>0&&<button onClick={()=>setPaused(v=>!v)}>{paused?'เล่นต่อ':'พักการเดินทาง'}</button>}</section>}
 <footer className="world-footer"><nav aria-label="เลือกธนาคาร">{banks.map(b=><button key={b.ticker} className={selected?.ticker===b.ticker?'active':''} onClick={()=>choose(b)}>{b.ticker}</button>)}</nav><div className="flow-legend"><span>● เงินทุน</span><span>● สินเชื่อ</span><span>● รายได้</span><span>● ความเสี่ยง</span></div><button onClick={()=>setPaused(p=>!p)}>{paused?'▶ เล่น':'Ⅱ พัก'}</button><small>ลากหมุน · คลิกขวาเลื่อน · Scroll ซูม · คลิกตึก/เส้นเงินเพื่อสำรวจ</small></footer>
 <details className="disclaimer"><summary>ข้อมูลและข้อจำกัด</summary><p>ข้อมูลจาก RAG ที่นำเข้า ยังไม่ได้ตรวจต้นฉบับซ้ำ · อัปเดตชุดข้อมูล {data?.updated??'N/A'}</p><p>ข้อมูลนี้จัดทำขึ้นเพื่อการศึกษาและการวิเคราะห์เท่านั้น ไม่ใช่คำแนะนำในการซื้อหรือขายหลักทรัพย์ ข้อมูลจาก AI หรือแบบจำลองอาจไม่ครบถ้วนหรือคลาดเคลื่อน นักลงทุนควรตรวจสอบข้อมูลจากแหล่งอ้างอิงและพิจารณาความเสี่ยงก่อนตัดสินใจลงทุน</p><p>ผลลัพธ์จากแบบจำลอง ไม่ใช่ประมาณการหรือ Guidance ของบริษัท</p></details>
 </main>
}
