export const sections = [
 {id:'funding',label:'เงินทุน',en:'FUNDING',color:'#56b9ed',children:[['deposits','เงินฝาก','ล้านบาท'],['casa','CASA','%'],['cost_deposit','ต้นทุนเงินฝาก','%'],['cost_fund','ต้นทุนเงินทุน','%'],['deposit_growth_ytd','เงินฝากเติบโต YTD','%']]},
 {id:'assets',label:'สินทรัพย์และสินเชื่อ',en:'LOAN ENGINE',color:'#68d9ad',children:[['assets','สินทรัพย์','ล้านบาท'],['loans','สินเชื่อ','ล้านบาท'],['loan_growth_ytd','สินเชื่อเติบโต YTD','%'],['ldr','Loan / Deposit','%']]},
 {id:'income',label:'รายได้และ NIM',en:'INTEREST ENGINE',color:'#efc57e',children:[['q2_nii','รายได้ดอกเบี้ยสุทธิ Q2','ล้านบาท'],['q2_noninterest','รายได้อื่น Q2','ล้านบาท'],['nim_q2','NIM Q2','%'],['q2_netfees','ค่าธรรมเนียมสุทธิ Q2','ล้านบาท']]},
 {id:'risk',label:'ความเสี่ยงและสำรอง',en:'RISK / PROVISION',color:'#ed8990',children:[['npl_pct','NPL','%'],['stage2_pct','Stage 2 / SICR','%'],['credit_cost_q2','Credit cost Q2','bps'],['coverage','Coverage','%'],['q2_ecl','ECL Q2','ล้านบาท']]},
 {id:'profit',label:'กำไรและประสิทธิภาพ',en:'PROFIT ENGINE',color:'#9cdcc4',children:[['q2_profit','กำไร Q2','ล้านบาท'],['h1_profit','กำไร H1','ล้านบาท'],['q2_opex','ค่าใช้จ่าย Q2','ล้านบาท'],['cost_income','Cost / Income','%'],['roe_q2','ROE Q2','%']]},
 {id:'capital',label:'ทุนและผู้ถือหุ้น',en:'CAPITAL',color:'#b4a1ef',children:[['equity_attrib','ส่วนผู้ถือหุ้น','ล้านบาท'],['car','CAR','%'],['tier1','Tier 1','%'],['cet1','CET1','%']]},
] as const;
export type SectionId = typeof sections[number]['id'];
export const sectionById = (id:string) => sections.find(s=>s.id===id);
export const definitions:Record<string,string>={nim_q2:'NIM คือรายได้ดอกเบี้ยสุทธิต่อสินทรัพย์ที่ก่อให้เกิดดอกเบี้ยเฉลี่ย วิธี annualize ให้ยึดตามรายงาน ไม่ใช่อัตรากู้ลบอัตราฝากโดยตรง',npl_pct:'หนี้ที่มีปัญหาตามนิยามของรายงาน NPL เพิ่มไม่ได้หมายความว่าจะเกิดขาดทุนจำนวนเดียวกันทันที',credit_cost_q2:'ต้นทุนสำรองเทียบสินเชื่อเฉลี่ย ตรวจวิธี annualize ในต้นฉบับ หน่วย bps: 100 bps = 1%',roe_q2:'กำไรเทียบทุนผู้ถือหุ้นเฉลี่ย ตามขอบเขตและวิธี annualize ของบริษัท ROE สูงต้องพิจารณาความเสี่ยงและเงินกองทุนร่วมด้วย',stage2_pct:'สินเชื่อที่ความเสี่ยงเพิ่มขึ้นอย่างมีนัยสำคัญ นิยาม SICR/Stage 2 อาจต่างกันตามรายงาน ไม่ใช่ NPL ทั้งหมด',car:'เงินกองทุนต่อสินทรัพย์เสี่ยง ต้องดูขอบเขตกลุ่มการเงินหรือธนาคารก่อนเปรียบเทียบ'};
